-- CreateTable
CREATE TABLE "apartment_city" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "MEGA_CD" TEXT NOT NULL,
    "MEGA_CD_NM" TEXT NOT NULL,
    "APT_HSMP_CO" INTEGER NOT NULL,
    "AE_66_SQMT_BELO_HSHLD_CO" INTEGER NOT NULL,
    "AE_66_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_99_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_132_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_165_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "PC_1_HDMIL_BELO_HSHLD_CO" INTEGER NOT NULL,
    "PC_1_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_2_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_3_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_4_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_5_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_6_HDMIL_ABOVE_HSHLD_CO" INTEGER NOT NULL,
    "AVRG_AE" INTEGER NOT NULL,
    "AVRG_MKTC" BIGINT NOT NULL,

    CONSTRAINT "apartment_city_pkey" PRIMARY KEY ("STDR_YYQU_CD","MEGA_CD")
);

-- CreateTable
CREATE TABLE "apartment_gu" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "APT_HSMP_CO" INTEGER NOT NULL,
    "AE_66_SQMT_BELO_HSHLD_CO" INTEGER NOT NULL,
    "AE_66_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_99_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_132_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_165_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "PC_1_HDMIL_BELO_HSHLD_CO" INTEGER NOT NULL,
    "PC_1_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_2_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_3_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_4_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_5_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_6_HDMIL_ABOVE_HSHLD_CO" INTEGER NOT NULL,
    "AVRG_AE" INTEGER NOT NULL,
    "AVRG_MKTC" BIGINT NOT NULL,

    CONSTRAINT "apartment_gu_pkey" PRIMARY KEY ("STDR_YYQU_CD","SIGNGU_CD")
);

-- CreateTable
CREATE TABLE "apartment_dong" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "APT_HSMP_CO" INTEGER NOT NULL,
    "AE_66_SQMT_BELO_HSHLD_CO" INTEGER NOT NULL,
    "AE_66_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_99_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_132_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_165_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "PC_1_HDMIL_BELO_HSHLD_CO" INTEGER NOT NULL,
    "PC_1_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_2_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_3_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_4_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_5_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_6_HDMIL_ABOVE_HSHLD_CO" INTEGER NOT NULL,
    "AVRG_AE" INTEGER NOT NULL,
    "AVRG_MKTC" BIGINT NOT NULL,

    CONSTRAINT "apartment_dong_pkey" PRIMARY KEY ("STDR_YYQU_CD","ADSTRD_CD")
);

-- CreateTable
CREATE TABLE "apartment_backarea" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "APT_HSMP_CO" INTEGER NOT NULL,
    "AE_66_SQMT_BELO_HSHLD_CO" INTEGER NOT NULL,
    "AE_66_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_99_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_132_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_165_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "PC_1_HDMIL_BELO_HSHLD_CO" INTEGER NOT NULL,
    "PC_1_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_2_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_3_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_4_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_5_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_6_HDMIL_ABOVE_HSHLD_CO" INTEGER NOT NULL,
    "AVRG_AE" INTEGER NOT NULL,
    "AVRG_MKTC" BIGINT NOT NULL,

    CONSTRAINT "apartment_backarea_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "apartment_commercial" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "APT_HSMP_CO" INTEGER NOT NULL,
    "AE_66_SQMT_BELO_HSHLD_CO" INTEGER NOT NULL,
    "AE_66_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_99_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_132_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "AE_165_SQMT_HSHLD_CO" INTEGER NOT NULL,
    "PC_1_HDMIL_BELO_HSHLD_CO" INTEGER NOT NULL,
    "PC_1_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_2_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_3_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_4_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_5_HDMIL_HSHLD_CO" INTEGER NOT NULL,
    "PC_6_HDMIL_ABOVE_HSHLD_CO" INTEGER NOT NULL,
    "AVRG_AE" INTEGER NOT NULL,
    "AVRG_MKTC" BIGINT NOT NULL,

    CONSTRAINT "apartment_commercial_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "area_city" (
    "MEGA_CD" TEXT NOT NULL,
    "MEGA_NM" TEXT NOT NULL,
    "XCNTS_VALUE" INTEGER NOT NULL,
    "YDNTS_VALUE" INTEGER NOT NULL,
    "RELM_AR" INTEGER NOT NULL,

    CONSTRAINT "area_city_pkey" PRIMARY KEY ("MEGA_CD")
);

-- CreateTable
CREATE TABLE "area_gu" (
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_NM" TEXT NOT NULL,
    "XCNTS_VALUE" INTEGER NOT NULL,
    "YDNTS_VALUE" INTEGER NOT NULL,
    "RELM_AR" INTEGER NOT NULL,

    CONSTRAINT "area_gu_pkey" PRIMARY KEY ("SIGNGU_CD")
);

-- CreateTable
CREATE TABLE "area_dong" (
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_NM" TEXT NOT NULL,
    "XCNTS_VALUE" INTEGER NOT NULL,
    "YDNTS_VALUE" INTEGER NOT NULL,
    "RELM_AR" INTEGER NOT NULL,

    CONSTRAINT "area_dong_pkey" PRIMARY KEY ("ADSTRD_CD")
);

-- CreateTable
CREATE TABLE "area_backarea" (
    "ALLEY_TRDAR_CD" TEXT NOT NULL,
    "ALLEY_TRDAR_NM" TEXT NOT NULL,
    "XCNTS_VALUE" INTEGER NOT NULL,
    "YDNTS_VALUE" INTEGER NOT NULL,
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "RELM_AR" INTEGER NOT NULL,

    CONSTRAINT "area_backarea_pkey" PRIMARY KEY ("ALLEY_TRDAR_CD")
);

-- CreateTable
CREATE TABLE "area_commercial" (
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "XCNTS_VALUE" INTEGER NOT NULL,
    "YDNTS_VALUE" INTEGER NOT NULL,
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "RELM_AR" INTEGER NOT NULL,

    CONSTRAINT "area_commercial_pkey" PRIMARY KEY ("TRDAR_CD")
);

-- CreateTable
CREATE TABLE "commercial_change_gu" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "TRDAR_CHNGE_IX" TEXT NOT NULL,
    "TRDAR_CHNGE_IX_NM" TEXT NOT NULL,
    "OPR_SALE_MT_AVRG" INTEGER NOT NULL,
    "CLS_SALE_MT_AVRG" INTEGER NOT NULL,
    "SU_OPR_SALE_MT_AVRG" INTEGER NOT NULL,
    "SU_CLS_SALE_MT_AVRG" INTEGER NOT NULL,

    CONSTRAINT "commercial_change_gu_pkey" PRIMARY KEY ("STDR_YYQU_CD","SIGNGU_CD")
);

-- CreateTable
CREATE TABLE "commercial_change_dong" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "TRDAR_CHNGE_IX" TEXT NOT NULL,
    "TRDAR_CHNGE_IX_NM" TEXT NOT NULL,
    "OPR_SALE_MT_AVRG" INTEGER NOT NULL,
    "CLS_SALE_MT_AVRG" INTEGER NOT NULL,
    "SU_OPR_SALE_MT_AVRG" INTEGER NOT NULL,
    "SU_CLS_SALE_MT_AVRG" INTEGER NOT NULL,

    CONSTRAINT "commercial_change_dong_pkey" PRIMARY KEY ("STDR_YYQU_CD","ADSTRD_CD")
);

-- CreateTable
CREATE TABLE "commercial_change_commercial" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "TRDAR_CHNGE_IX" TEXT NOT NULL,
    "TRDAR_CHNGE_IX_NM" TEXT NOT NULL,
    "OPR_SALE_MT_AVRG" INTEGER NOT NULL,
    "CLS_SALE_MT_AVRG" INTEGER NOT NULL,
    "SU_OPR_SALE_MT_AVRG" INTEGER NOT NULL,
    "SU_CLS_SALE_MT_AVRG" INTEGER NOT NULL,

    CONSTRAINT "commercial_change_commercial_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "facility_city" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "MEGA_CD" TEXT NOT NULL,
    "MEGA_CD_NM" TEXT NOT NULL,
    "VIATR_FCLTY_CO" INTEGER NOT NULL,
    "PBLOFC_CO" INTEGER NOT NULL,
    "BANK_CO" INTEGER NOT NULL,
    "GEHSPT_CO" INTEGER NOT NULL,
    "GNRL_HSPTL_CO" INTEGER NOT NULL,
    "PARMACY_CO" INTEGER NOT NULL,
    "KNDRGR_CO" INTEGER NOT NULL,
    "ELESCH_CO" INTEGER NOT NULL,
    "MSKUL_CO" INTEGER NOT NULL,
    "HGSCHL_CO" INTEGER NOT NULL,
    "UNIV_CO" INTEGER NOT NULL,
    "DRTS_CO" INTEGER NOT NULL,
    "SUPMK_CO" INTEGER NOT NULL,
    "THEAT_CO" INTEGER NOT NULL,
    "STAYNG_FCLTY_CO" INTEGER NOT NULL,
    "ARPRT_CO" INTEGER NOT NULL,
    "RLROAD_STATN_CO" INTEGER NOT NULL,
    "BUS_TRMINL_CO" INTEGER NOT NULL,
    "SUBWAY_STATN_CO" INTEGER NOT NULL,
    "BUS_STTN_CO" INTEGER NOT NULL,

    CONSTRAINT "facility_city_pkey" PRIMARY KEY ("STDR_YYQU_CD","MEGA_CD")
);

-- CreateTable
CREATE TABLE "facility_gu" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "VIATR_FCLTY_CO" INTEGER NOT NULL,
    "PBLOFC_CO" INTEGER NOT NULL,
    "BANK_CO" INTEGER NOT NULL,
    "GEHSPT_CO" INTEGER NOT NULL,
    "GNRL_HSPTL_CO" INTEGER NOT NULL,
    "PARMACY_CO" INTEGER NOT NULL,
    "KNDRGR_CO" INTEGER NOT NULL,
    "ELESCH_CO" INTEGER NOT NULL,
    "MSKUL_CO" INTEGER NOT NULL,
    "HGSCHL_CO" INTEGER NOT NULL,
    "UNIV_CO" INTEGER NOT NULL,
    "DRTS_CO" INTEGER NOT NULL,
    "SUPMK_CO" INTEGER NOT NULL,
    "THEAT_CO" INTEGER NOT NULL,
    "STAYNG_FCLTY_CO" INTEGER NOT NULL,
    "ARPRT_CO" INTEGER NOT NULL,
    "RLROAD_STATN_CO" INTEGER NOT NULL,
    "BUS_TRMINL_CO" INTEGER NOT NULL,
    "SUBWAY_STATN_CO" INTEGER NOT NULL,
    "BUS_STTN_CO" INTEGER NOT NULL,

    CONSTRAINT "facility_gu_pkey" PRIMARY KEY ("STDR_YYQU_CD","SIGNGU_CD")
);

-- CreateTable
CREATE TABLE "facility_dong" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "VIATR_FCLTY_CO" INTEGER NOT NULL,
    "PBLOFC_CO" INTEGER NOT NULL,
    "BANK_CO" INTEGER NOT NULL,
    "GEHSPT_CO" INTEGER NOT NULL,
    "GNRL_HSPTL_CO" INTEGER NOT NULL,
    "PARMACY_CO" INTEGER NOT NULL,
    "KNDRGR_CO" INTEGER NOT NULL,
    "ELESCH_CO" INTEGER NOT NULL,
    "MSKUL_CO" INTEGER NOT NULL,
    "HGSCHL_CO" INTEGER NOT NULL,
    "UNIV_CO" INTEGER NOT NULL,
    "DRTS_CO" INTEGER NOT NULL,
    "SUPMK_CO" INTEGER NOT NULL,
    "THEAT_CO" INTEGER NOT NULL,
    "STAYNG_FCLTY_CO" INTEGER NOT NULL,
    "ARPRT_CO" INTEGER NOT NULL,
    "RLROAD_STATN_CO" INTEGER NOT NULL,
    "BUS_TRMINL_CO" INTEGER NOT NULL,
    "SUBWAY_STATN_CO" INTEGER NOT NULL,
    "BUS_STTN_CO" INTEGER NOT NULL,

    CONSTRAINT "facility_dong_pkey" PRIMARY KEY ("STDR_YYQU_CD","ADSTRD_CD")
);

-- CreateTable
CREATE TABLE "facility_backarea" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "VIATR_FCLTY_CO" INTEGER NOT NULL,
    "PBLOFC_CO" INTEGER NOT NULL,
    "BANK_CO" INTEGER NOT NULL,
    "GEHSPT_CO" INTEGER NOT NULL,
    "GNRL_HSPTL_CO" INTEGER NOT NULL,
    "PARMACY_CO" INTEGER NOT NULL,
    "KNDRGR_CO" INTEGER NOT NULL,
    "ELESCH_CO" INTEGER NOT NULL,
    "MSKUL_CO" INTEGER NOT NULL,
    "HGSCHL_CO" INTEGER NOT NULL,
    "UNIV_CO" INTEGER NOT NULL,
    "DRTS_CO" INTEGER NOT NULL,
    "SUPMK_CO" INTEGER NOT NULL,
    "THEAT_CO" INTEGER NOT NULL,
    "STAYNG_FCLTY_CO" INTEGER NOT NULL,
    "ARPRT_CO" INTEGER NOT NULL,
    "RLROAD_STATN_CO" INTEGER NOT NULL,
    "BUS_TRMINL_CO" INTEGER NOT NULL,
    "SUBWAY_STATN_CO" INTEGER NOT NULL,
    "BUS_STTN_CO" INTEGER NOT NULL,

    CONSTRAINT "facility_backarea_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "facility_commercial" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "VIATR_FCLTY_CO" INTEGER NOT NULL,
    "PBLOFC_CO" INTEGER NOT NULL,
    "BANK_CO" INTEGER NOT NULL,
    "GEHSPT_CO" INTEGER NOT NULL,
    "GNRL_HSPTL_CO" INTEGER NOT NULL,
    "PARMACY_CO" INTEGER NOT NULL,
    "KNDRGR_CO" INTEGER NOT NULL,
    "ELESCH_CO" INTEGER NOT NULL,
    "MSKUL_CO" INTEGER NOT NULL,
    "HGSCHL_CO" INTEGER NOT NULL,
    "UNIV_CO" INTEGER NOT NULL,
    "DRTS_CO" INTEGER NOT NULL,
    "SUPMK_CO" INTEGER NOT NULL,
    "THEAT_CO" INTEGER NOT NULL,
    "STAYNG_FCLTY_CO" INTEGER NOT NULL,
    "ARPRT_CO" INTEGER NOT NULL,
    "RLROAD_STATN_CO" INTEGER NOT NULL,
    "BUS_TRMINL_CO" INTEGER NOT NULL,
    "SUBWAY_STATN_CO" INTEGER NOT NULL,
    "BUS_STTN_CO" INTEGER NOT NULL,

    CONSTRAINT "facility_commercial_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "foot_traffic_city" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "MEGA_CD" TEXT NOT NULL,
    "MEGA_CD_NM" TEXT NOT NULL,
    "TOT_FLPOP_CO" BIGINT NOT NULL,
    "ML_FLPOP_CO" BIGINT NOT NULL,
    "FML_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_10_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_20_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_30_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_40_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_50_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_60_ABOVE_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_00_06_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_06_11_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_11_14_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_14_17_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_17_21_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_21_24_FLPOP_CO" BIGINT NOT NULL,
    "MON_FLPOP_CO" BIGINT NOT NULL,
    "TUES_FLPOP_CO" BIGINT NOT NULL,
    "WED_FLPOP_CO" BIGINT NOT NULL,
    "THUR_FLPOP_CO" BIGINT NOT NULL,
    "FRI_FLPOP_CO" BIGINT NOT NULL,
    "SAT_FLPOP_CO" BIGINT NOT NULL,
    "SUN_FLPOP_CO" BIGINT NOT NULL,

    CONSTRAINT "foot_traffic_city_pkey" PRIMARY KEY ("STDR_YYQU_CD","MEGA_CD")
);

-- CreateTable
CREATE TABLE "foot_traffic_gu" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "TOT_FLPOP_CO" BIGINT NOT NULL,
    "ML_FLPOP_CO" BIGINT NOT NULL,
    "FML_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_10_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_20_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_30_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_40_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_50_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_60_ABOVE_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_00_06_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_06_11_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_11_14_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_14_17_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_17_21_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_21_24_FLPOP_CO" BIGINT NOT NULL,
    "MON_FLPOP_CO" BIGINT NOT NULL,
    "TUES_FLPOP_CO" BIGINT NOT NULL,
    "WED_FLPOP_CO" BIGINT NOT NULL,
    "THUR_FLPOP_CO" BIGINT NOT NULL,
    "FRI_FLPOP_CO" BIGINT NOT NULL,
    "SAT_FLPOP_CO" BIGINT NOT NULL,
    "SUN_FLPOP_CO" BIGINT NOT NULL,

    CONSTRAINT "foot_traffic_gu_pkey" PRIMARY KEY ("STDR_YYQU_CD","SIGNGU_CD")
);

-- CreateTable
CREATE TABLE "foot_traffic_dong" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "TOT_FLPOP_CO" BIGINT NOT NULL,
    "ML_FLPOP_CO" BIGINT NOT NULL,
    "FML_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_10_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_20_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_30_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_40_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_50_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_60_ABOVE_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_00_06_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_06_11_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_11_14_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_14_17_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_17_21_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_21_24_FLPOP_CO" BIGINT NOT NULL,
    "MON_FLPOP_CO" BIGINT NOT NULL,
    "TUES_FLPOP_CO" BIGINT NOT NULL,
    "WED_FLPOP_CO" BIGINT NOT NULL,
    "THUR_FLPOP_CO" BIGINT NOT NULL,
    "FRI_FLPOP_CO" BIGINT NOT NULL,
    "SAT_FLPOP_CO" BIGINT NOT NULL,
    "SUN_FLPOP_CO" BIGINT NOT NULL,

    CONSTRAINT "foot_traffic_dong_pkey" PRIMARY KEY ("STDR_YYQU_CD","ADSTRD_CD")
);

-- CreateTable
CREATE TABLE "foot_traffic_backarea" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "TOT_FLPOP_CO" BIGINT NOT NULL,
    "ML_FLPOP_CO" BIGINT NOT NULL,
    "FML_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_10_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_20_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_30_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_40_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_50_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_60_ABOVE_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_00_06_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_06_11_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_11_14_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_14_17_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_17_21_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_21_24_FLPOP_CO" BIGINT NOT NULL,
    "MON_FLPOP_CO" BIGINT NOT NULL,
    "TUES_FLPOP_CO" BIGINT NOT NULL,
    "WED_FLPOP_CO" BIGINT NOT NULL,
    "THUR_FLPOP_CO" BIGINT NOT NULL,
    "FRI_FLPOP_CO" BIGINT NOT NULL,
    "SAT_FLPOP_CO" BIGINT NOT NULL,
    "SUN_FLPOP_CO" BIGINT NOT NULL,

    CONSTRAINT "foot_traffic_backarea_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "foot_traffic_commercial" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "TOT_FLPOP_CO" BIGINT NOT NULL,
    "ML_FLPOP_CO" BIGINT NOT NULL,
    "FML_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_10_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_20_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_30_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_40_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_50_FLPOP_CO" BIGINT NOT NULL,
    "AGRDE_60_ABOVE_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_00_06_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_06_11_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_11_14_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_14_17_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_17_21_FLPOP_CO" BIGINT NOT NULL,
    "TMZON_21_24_FLPOP_CO" BIGINT NOT NULL,
    "MON_FLPOP_CO" BIGINT NOT NULL,
    "TUES_FLPOP_CO" BIGINT NOT NULL,
    "WED_FLPOP_CO" BIGINT NOT NULL,
    "THUR_FLPOP_CO" BIGINT NOT NULL,
    "FRI_FLPOP_CO" BIGINT NOT NULL,
    "SAT_FLPOP_CO" BIGINT NOT NULL,
    "SUN_FLPOP_CO" BIGINT NOT NULL,

    CONSTRAINT "foot_traffic_commercial_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "income_consumption_city" (
    "MEGA_CD" TEXT NOT NULL,
    "STDR_YYQU_CD" TEXT NOT NULL,
    "MEGA_CD_NM" TEXT NOT NULL,
    "MT_AVRG_INCOME_AMT" INTEGER NOT NULL,
    "INCOME_SCTN_CD" TEXT NOT NULL,
    "EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "FDSTFFS_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "CLTHS_FTWR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "LVSPL_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "MCP_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "TRNSPORT_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "EDC_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "PLESR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "LSR_CLTUR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "ETC_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "FD_EXPNDTR_TOTAMT" BIGINT NOT NULL,

    CONSTRAINT "income_consumption_city_pkey" PRIMARY KEY ("STDR_YYQU_CD","MEGA_CD")
);

-- CreateTable
CREATE TABLE "income_consumption_gu" (
    "SIGNGU_CD" TEXT NOT NULL,
    "STDR_YYQU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "MT_AVRG_INCOME_AMT" INTEGER NOT NULL,
    "INCOME_SCTN_CD" TEXT NOT NULL,
    "EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "FDSTFFS_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "CLTHS_FTWR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "LVSPL_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "MCP_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "TRNSPORT_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "EDC_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "PLESR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "LSR_CLTUR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "ETC_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "FD_EXPNDTR_TOTAMT" BIGINT NOT NULL,

    CONSTRAINT "income_consumption_gu_pkey" PRIMARY KEY ("STDR_YYQU_CD","SIGNGU_CD")
);

-- CreateTable
CREATE TABLE "income_consumption_dong" (
    "ADSTRD_CD" TEXT NOT NULL,
    "STDR_YYQU_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "MT_AVRG_INCOME_AMT" INTEGER NOT NULL,
    "INCOME_SCTN_CD" TEXT NOT NULL,
    "EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "FDSTFFS_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "CLTHS_FTWR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "LVSPL_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "MCP_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "TRNSPORT_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "EDC_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "PLESR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "LSR_CLTUR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "ETC_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "FD_EXPNDTR_TOTAMT" BIGINT NOT NULL,

    CONSTRAINT "income_consumption_dong_pkey" PRIMARY KEY ("STDR_YYQU_CD","ADSTRD_CD")
);

-- CreateTable
CREATE TABLE "income_consumption_backarea" (
    "TRDAR_SE_CD" TEXT NOT NULL,
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "MT_AVRG_INCOME_AMT" INTEGER NOT NULL,
    "INCOME_SCTN_CD" TEXT NOT NULL,
    "EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "FDSTFFS_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "CLTHS_FTWR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "LVSPL_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "MCP_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "TRNSPORT_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "LSR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "CLTUR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "EDC_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "PLESR_EXPNDTR_TOTAMT" BIGINT NOT NULL,

    CONSTRAINT "income_consumption_backarea_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "income_consumption_commercial" (
    "TRDAR_SE_CD" TEXT NOT NULL,
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "MT_AVRG_INCOME_AMT" INTEGER NOT NULL,
    "INCOME_SCTN_CD" TEXT NOT NULL,
    "EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "FDSTFFS_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "CLTHS_FTWR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "LVSPL_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "MCP_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "TRNSPORT_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "LSR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "CLTUR_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "EDC_EXPNDTR_TOTAMT" BIGINT NOT NULL,
    "PLESR_EXPNDTR_TOTAMT" BIGINT NOT NULL,

    CONSTRAINT "income_consumption_commercial_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "resident_population_city" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "MEGA_CD" TEXT NOT NULL,
    "MEGA_CD_NM" TEXT NOT NULL,
    "TOT_REPOP_CO" INTEGER NOT NULL,
    "ML_REPOP_CO" INTEGER NOT NULL,
    "FML_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_10_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_20_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_30_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_40_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_50_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "MAG_10_REPOP_CO" INTEGER NOT NULL,
    "MAG_20_REPOP_CO" INTEGER NOT NULL,
    "MAG_30_REPOP_CO" INTEGER NOT NULL,
    "MAG_40_REPOP_CO" INTEGER NOT NULL,
    "MAG_50_REPOP_CO" INTEGER NOT NULL,
    "MAG_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "FAG_10_REPOP_CO" INTEGER NOT NULL,
    "FAG_20_REPOP_CO" INTEGER NOT NULL,
    "FAG_30_REPOP_CO" INTEGER NOT NULL,
    "FAG_40_REPOP_CO" INTEGER NOT NULL,
    "FAG_50_REPOP_CO" INTEGER NOT NULL,
    "FAG_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "TOT_HSHLD_CO" INTEGER NOT NULL,
    "APT_HSHLD_CO" INTEGER NOT NULL,
    "NON_APT_HSHLD_CO" INTEGER NOT NULL,

    CONSTRAINT "resident_population_city_pkey" PRIMARY KEY ("STDR_YYQU_CD","MEGA_CD")
);

-- CreateTable
CREATE TABLE "resident_population_gu" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "TOT_REPOP_CO" INTEGER NOT NULL,
    "ML_REPOP_CO" INTEGER NOT NULL,
    "FML_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_10_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_20_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_30_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_40_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_50_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "MAG_10_REPOP_CO" INTEGER NOT NULL,
    "MAG_20_REPOP_CO" INTEGER NOT NULL,
    "MAG_30_REPOP_CO" INTEGER NOT NULL,
    "MAG_40_REPOP_CO" INTEGER NOT NULL,
    "MAG_50_REPOP_CO" INTEGER NOT NULL,
    "MAG_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "FAG_10_REPOP_CO" INTEGER NOT NULL,
    "FAG_20_REPOP_CO" INTEGER NOT NULL,
    "FAG_30_REPOP_CO" INTEGER NOT NULL,
    "FAG_40_REPOP_CO" INTEGER NOT NULL,
    "FAG_50_REPOP_CO" INTEGER NOT NULL,
    "FAG_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "TOT_HSHLD_CO" INTEGER NOT NULL,
    "APT_HSHLD_CO" INTEGER NOT NULL,
    "NON_APT_HSHLD_CO" INTEGER NOT NULL,

    CONSTRAINT "resident_population_gu_pkey" PRIMARY KEY ("STDR_YYQU_CD","SIGNGU_CD")
);

-- CreateTable
CREATE TABLE "resident_population_dong" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "TOT_REPOP_CO" INTEGER NOT NULL,
    "ML_REPOP_CO" INTEGER NOT NULL,
    "FML_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_10_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_20_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_30_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_40_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_50_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "MAG_10_REPOP_CO" INTEGER NOT NULL,
    "MAG_20_REPOP_CO" INTEGER NOT NULL,
    "MAG_30_REPOP_CO" INTEGER NOT NULL,
    "MAG_40_REPOP_CO" INTEGER NOT NULL,
    "MAG_50_REPOP_CO" INTEGER NOT NULL,
    "MAG_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "FAG_10_REPOP_CO" INTEGER NOT NULL,
    "FAG_20_REPOP_CO" INTEGER NOT NULL,
    "FAG_30_REPOP_CO" INTEGER NOT NULL,
    "FAG_40_REPOP_CO" INTEGER NOT NULL,
    "FAG_50_REPOP_CO" INTEGER NOT NULL,
    "FAG_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "TOT_HSHLD_CO" INTEGER NOT NULL,
    "APT_HSHLD_CO" INTEGER NOT NULL,
    "NON_APT_HSHLD_CO" INTEGER NOT NULL,

    CONSTRAINT "resident_population_dong_pkey" PRIMARY KEY ("STDR_YYQU_CD","ADSTRD_CD")
);

-- CreateTable
CREATE TABLE "resident_population_backarea" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "TOT_REPOP_CO" INTEGER NOT NULL,
    "ML_REPOP_CO" INTEGER NOT NULL,
    "FML_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_10_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_20_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_30_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_40_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_50_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "MAG_10_REPOP_CO" INTEGER NOT NULL,
    "MAG_20_REPOP_CO" INTEGER NOT NULL,
    "MAG_30_REPOP_CO" INTEGER NOT NULL,
    "MAG_40_REPOP_CO" INTEGER NOT NULL,
    "MAG_50_REPOP_CO" INTEGER NOT NULL,
    "MAG_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "FAG_10_REPOP_CO" INTEGER NOT NULL,
    "FAG_20_REPOP_CO" INTEGER NOT NULL,
    "FAG_30_REPOP_CO" INTEGER NOT NULL,
    "FAG_40_REPOP_CO" INTEGER NOT NULL,
    "FAG_50_REPOP_CO" INTEGER NOT NULL,
    "FAG_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "TOT_HSHLD_CO" INTEGER NOT NULL,
    "APT_HSHLD_CO" INTEGER NOT NULL,
    "NON_APT_HSHLD_CO" INTEGER NOT NULL,

    CONSTRAINT "resident_population_backarea_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "resident_population_commercial" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "TOT_REPOP_CO" INTEGER NOT NULL,
    "ML_REPOP_CO" INTEGER NOT NULL,
    "FML_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_10_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_20_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_30_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_40_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_50_REPOP_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "MAG_10_REPOP_CO" INTEGER NOT NULL,
    "MAG_20_REPOP_CO" INTEGER NOT NULL,
    "MAG_30_REPOP_CO" INTEGER NOT NULL,
    "MAG_40_REPOP_CO" INTEGER NOT NULL,
    "MAG_50_REPOP_CO" INTEGER NOT NULL,
    "MAG_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "FAG_10_REPOP_CO" INTEGER NOT NULL,
    "FAG_20_REPOP_CO" INTEGER NOT NULL,
    "FAG_30_REPOP_CO" INTEGER NOT NULL,
    "FAG_40_REPOP_CO" INTEGER NOT NULL,
    "FAG_50_REPOP_CO" INTEGER NOT NULL,
    "FAG_60_ABOVE_REPOP_CO" INTEGER NOT NULL,
    "TOT_HSHLD_CO" INTEGER NOT NULL,
    "APT_HSHLD_CO" INTEGER NOT NULL,
    "NON_APT_HSHLD_CO" INTEGER NOT NULL,

    CONSTRAINT "resident_population_commercial_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "sales_city" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "MEGA_CD" TEXT NOT NULL,
    "MEGA_CD_NM" TEXT NOT NULL,
    "SVC_INDUTY_CD" TEXT NOT NULL,
    "SVC_INDUTY_CD_NM" TEXT NOT NULL,
    "THSMON_SELNG_AMT" BIGINT NOT NULL,
    "THSMON_SELNG_CO" INTEGER NOT NULL,
    "MDWK_SELNG_AMT" BIGINT NOT NULL,
    "WKEND_SELNG_AMT" BIGINT NOT NULL,
    "MON_SELNG_AMT" BIGINT NOT NULL,
    "TUES_SELNG_AMT" BIGINT NOT NULL,
    "WED_SELNG_AMT" BIGINT NOT NULL,
    "THUR_SELNG_AMT" BIGINT NOT NULL,
    "FRI_SELNG_AMT" BIGINT NOT NULL,
    "SAT_SELNG_AMT" BIGINT NOT NULL,
    "SUN_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_00_06_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_06_11_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_11_14_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_14_17_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_17_21_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_21_24_SELNG_AMT" BIGINT NOT NULL,
    "ML_SELNG_AMT" BIGINT NOT NULL,
    "FML_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_10_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_20_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_30_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_40_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_50_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_60_ABOVE_SELNG_AMT" BIGINT NOT NULL,
    "MDWK_SELNG_CO" INTEGER NOT NULL,
    "WKEND_SELNG_CO" INTEGER NOT NULL,
    "MON_SELNG_CO" INTEGER NOT NULL,
    "TUES_SELNG_CO" INTEGER NOT NULL,
    "WED_SELNG_CO" INTEGER NOT NULL,
    "THUR_SELNG_CO" INTEGER NOT NULL,
    "FRI_SELNG_CO" INTEGER NOT NULL,
    "SAT_SELNG_CO" INTEGER NOT NULL,
    "SUN_SELNG_CO" INTEGER NOT NULL,
    "TMZON_00_06_SELNG_CO" INTEGER NOT NULL,
    "TMZON_06_11_SELNG_CO" INTEGER NOT NULL,
    "TMZON_11_14_SELNG_CO" INTEGER NOT NULL,
    "TMZON_14_17_SELNG_CO" INTEGER NOT NULL,
    "TMZON_17_21_SELNG_CO" INTEGER NOT NULL,
    "TMZON_21_24_SELNG_CO" INTEGER NOT NULL,
    "ML_SELNG_CO" INTEGER NOT NULL,
    "FML_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_10_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_20_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_30_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_40_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_50_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_SELNG_CO" INTEGER NOT NULL,

    CONSTRAINT "sales_city_pkey" PRIMARY KEY ("STDR_YYQU_CD","MEGA_CD","SVC_INDUTY_CD")
);

-- CreateTable
CREATE TABLE "sales_gu" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "SVC_INDUTY_CD" TEXT NOT NULL,
    "SVC_INDUTY_CD_NM" TEXT NOT NULL,
    "THSMON_SELNG_AMT" BIGINT NOT NULL,
    "THSMON_SELNG_CO" INTEGER NOT NULL,
    "MDWK_SELNG_AMT" BIGINT NOT NULL,
    "WKEND_SELNG_AMT" BIGINT NOT NULL,
    "MON_SELNG_AMT" BIGINT NOT NULL,
    "TUES_SELNG_AMT" BIGINT NOT NULL,
    "WED_SELNG_AMT" BIGINT NOT NULL,
    "THUR_SELNG_AMT" BIGINT NOT NULL,
    "FRI_SELNG_AMT" BIGINT NOT NULL,
    "SAT_SELNG_AMT" BIGINT NOT NULL,
    "SUN_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_00_06_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_06_11_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_11_14_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_14_17_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_17_21_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_21_24_SELNG_AMT" BIGINT NOT NULL,
    "ML_SELNG_AMT" BIGINT NOT NULL,
    "FML_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_10_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_20_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_30_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_40_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_50_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_60_ABOVE_SELNG_AMT" BIGINT NOT NULL,
    "MDWK_SELNG_CO" INTEGER NOT NULL,
    "WKEND_SELNG_CO" INTEGER NOT NULL,
    "MON_SELNG_CO" INTEGER NOT NULL,
    "TUES_SELNG_CO" INTEGER NOT NULL,
    "WED_SELNG_CO" INTEGER NOT NULL,
    "THUR_SELNG_CO" INTEGER NOT NULL,
    "FRI_SELNG_CO" INTEGER NOT NULL,
    "SAT_SELNG_CO" INTEGER NOT NULL,
    "SUN_SELNG_CO" INTEGER NOT NULL,
    "TMZON_00_06_SELNG_CO" INTEGER NOT NULL,
    "TMZON_06_11_SELNG_CO" INTEGER NOT NULL,
    "TMZON_11_14_SELNG_CO" INTEGER NOT NULL,
    "TMZON_14_17_SELNG_CO" INTEGER NOT NULL,
    "TMZON_17_21_SELNG_CO" INTEGER NOT NULL,
    "TMZON_21_24_SELNG_CO" INTEGER NOT NULL,
    "ML_SELNG_CO" INTEGER NOT NULL,
    "FML_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_10_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_20_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_30_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_40_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_50_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_SELNG_CO" INTEGER NOT NULL,

    CONSTRAINT "sales_gu_pkey" PRIMARY KEY ("STDR_YYQU_CD","SIGNGU_CD","SVC_INDUTY_CD")
);

-- CreateTable
CREATE TABLE "sales_dong" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "SVC_INDUTY_CD" TEXT NOT NULL,
    "SVC_INDUTY_CD_NM" TEXT NOT NULL,
    "THSMON_SELNG_AMT" BIGINT NOT NULL,
    "THSMON_SELNG_CO" INTEGER NOT NULL,
    "MDWK_SELNG_AMT" BIGINT NOT NULL,
    "WKEND_SELNG_AMT" BIGINT NOT NULL,
    "MON_SELNG_AMT" BIGINT NOT NULL,
    "TUES_SELNG_AMT" BIGINT NOT NULL,
    "WED_SELNG_AMT" BIGINT NOT NULL,
    "THUR_SELNG_AMT" BIGINT NOT NULL,
    "FRI_SELNG_AMT" BIGINT NOT NULL,
    "SAT_SELNG_AMT" BIGINT NOT NULL,
    "SUN_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_00_06_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_06_11_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_11_14_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_14_17_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_17_21_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_21_24_SELNG_AMT" BIGINT NOT NULL,
    "ML_SELNG_AMT" BIGINT NOT NULL,
    "FML_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_10_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_20_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_30_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_40_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_50_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_60_ABOVE_SELNG_AMT" BIGINT NOT NULL,
    "MDWK_SELNG_CO" INTEGER NOT NULL,
    "WKEND_SELNG_CO" INTEGER NOT NULL,
    "MON_SELNG_CO" INTEGER NOT NULL,
    "TUES_SELNG_CO" INTEGER NOT NULL,
    "WED_SELNG_CO" INTEGER NOT NULL,
    "THUR_SELNG_CO" INTEGER NOT NULL,
    "FRI_SELNG_CO" INTEGER NOT NULL,
    "SAT_SELNG_CO" INTEGER NOT NULL,
    "SUN_SELNG_CO" INTEGER NOT NULL,
    "TMZON_00_06_SELNG_CO" INTEGER NOT NULL,
    "TMZON_06_11_SELNG_CO" INTEGER NOT NULL,
    "TMZON_11_14_SELNG_CO" INTEGER NOT NULL,
    "TMZON_14_17_SELNG_CO" INTEGER NOT NULL,
    "TMZON_17_21_SELNG_CO" INTEGER NOT NULL,
    "TMZON_21_24_SELNG_CO" INTEGER NOT NULL,
    "ML_SELNG_CO" INTEGER NOT NULL,
    "FML_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_10_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_20_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_30_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_40_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_50_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_SELNG_CO" INTEGER NOT NULL,

    CONSTRAINT "sales_dong_pkey" PRIMARY KEY ("STDR_YYQU_CD","ADSTRD_CD","SVC_INDUTY_CD")
);

-- CreateTable
CREATE TABLE "sales_backarea" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "SVC_INDUTY_CD" TEXT NOT NULL,
    "SVC_INDUTY_CD_NM" TEXT NOT NULL,
    "THSMON_SELNG_AMT" BIGINT NOT NULL,
    "THSMON_SELNG_CO" INTEGER NOT NULL,
    "MDWK_SELNG_AMT" BIGINT NOT NULL,
    "WKEND_SELNG_AMT" BIGINT NOT NULL,
    "MON_SELNG_AMT" BIGINT NOT NULL,
    "TUES_SELNG_AMT" BIGINT NOT NULL,
    "WED_SELNG_AMT" BIGINT NOT NULL,
    "THUR_SELNG_AMT" BIGINT NOT NULL,
    "FRI_SELNG_AMT" BIGINT NOT NULL,
    "SAT_SELNG_AMT" BIGINT NOT NULL,
    "SUN_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_00_06_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_06_11_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_11_14_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_14_17_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_17_21_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_21_24_SELNG_AMT" BIGINT NOT NULL,
    "ML_SELNG_AMT" BIGINT NOT NULL,
    "FML_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_10_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_20_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_30_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_40_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_50_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_60_ABOVE_SELNG_AMT" BIGINT NOT NULL,
    "MDWK_SELNG_CO" INTEGER NOT NULL,
    "WKEND_SELNG_CO" INTEGER NOT NULL,
    "MON_SELNG_CO" INTEGER NOT NULL,
    "TUES_SELNG_CO" INTEGER NOT NULL,
    "WED_SELNG_CO" INTEGER NOT NULL,
    "THUR_SELNG_CO" INTEGER NOT NULL,
    "FRI_SELNG_CO" INTEGER NOT NULL,
    "SAT_SELNG_CO" INTEGER NOT NULL,
    "SUN_SELNG_CO" INTEGER NOT NULL,
    "TMZON_00_06_SELNG_CO" INTEGER NOT NULL,
    "TMZON_06_11_SELNG_CO" INTEGER NOT NULL,
    "TMZON_11_14_SELNG_CO" INTEGER NOT NULL,
    "TMZON_14_17_SELNG_CO" INTEGER NOT NULL,
    "TMZON_17_21_SELNG_CO" INTEGER NOT NULL,
    "TMZON_21_24_SELNG_CO" INTEGER NOT NULL,
    "ML_SELNG_CO" INTEGER NOT NULL,
    "FML_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_10_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_20_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_30_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_40_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_50_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_SELNG_CO" INTEGER NOT NULL,

    CONSTRAINT "sales_backarea_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD","SVC_INDUTY_CD")
);

-- CreateTable
CREATE TABLE "sales_commercial" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "SVC_INDUTY_CD" TEXT NOT NULL,
    "SVC_INDUTY_CD_NM" TEXT NOT NULL,
    "THSMON_SELNG_AMT" BIGINT NOT NULL,
    "THSMON_SELNG_CO" INTEGER NOT NULL,
    "MDWK_SELNG_AMT" BIGINT NOT NULL,
    "WKEND_SELNG_AMT" BIGINT NOT NULL,
    "MON_SELNG_AMT" BIGINT NOT NULL,
    "TUES_SELNG_AMT" BIGINT NOT NULL,
    "WED_SELNG_AMT" BIGINT NOT NULL,
    "THUR_SELNG_AMT" BIGINT NOT NULL,
    "FRI_SELNG_AMT" BIGINT NOT NULL,
    "SAT_SELNG_AMT" BIGINT NOT NULL,
    "SUN_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_00_06_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_06_11_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_11_14_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_14_17_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_17_21_SELNG_AMT" BIGINT NOT NULL,
    "TMZON_21_24_SELNG_AMT" BIGINT NOT NULL,
    "ML_SELNG_AMT" BIGINT NOT NULL,
    "FML_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_10_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_20_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_30_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_40_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_50_SELNG_AMT" BIGINT NOT NULL,
    "AGRDE_60_ABOVE_SELNG_AMT" BIGINT NOT NULL,
    "MDWK_SELNG_CO" INTEGER NOT NULL,
    "WKEND_SELNG_CO" INTEGER NOT NULL,
    "MON_SELNG_CO" INTEGER NOT NULL,
    "TUES_SELNG_CO" INTEGER NOT NULL,
    "WED_SELNG_CO" INTEGER NOT NULL,
    "THUR_SELNG_CO" INTEGER NOT NULL,
    "FRI_SELNG_CO" INTEGER NOT NULL,
    "SAT_SELNG_CO" INTEGER NOT NULL,
    "SUN_SELNG_CO" INTEGER NOT NULL,
    "TMZON_00_06_SELNG_CO" INTEGER NOT NULL,
    "TMZON_06_11_SELNG_CO" INTEGER NOT NULL,
    "TMZON_11_14_SELNG_CO" INTEGER NOT NULL,
    "TMZON_14_17_SELNG_CO" INTEGER NOT NULL,
    "TMZON_17_21_SELNG_CO" INTEGER NOT NULL,
    "TMZON_21_24_SELNG_CO" INTEGER NOT NULL,
    "ML_SELNG_CO" INTEGER NOT NULL,
    "FML_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_10_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_20_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_30_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_40_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_50_SELNG_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_SELNG_CO" INTEGER NOT NULL,

    CONSTRAINT "sales_commercial_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD","SVC_INDUTY_CD")
);

-- CreateTable
CREATE TABLE "store_city" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "MEGA_CD" TEXT NOT NULL,
    "MEGA_CD_NM" TEXT NOT NULL,
    "SVC_INDUTY_CD" TEXT NOT NULL,
    "SVC_INDUTY_CD_NM" TEXT NOT NULL,
    "STOR_CO" INTEGER NOT NULL,
    "SIMILR_INDUTY_STOR_CO" INTEGER NOT NULL,
    "OPBIZ_RT" DOUBLE PRECISION NOT NULL,
    "OPBIZ_STOR_CO" INTEGER NOT NULL,
    "CLSBIZ_RT" DOUBLE PRECISION NOT NULL,
    "CLSBIZ_STOR_CO" INTEGER NOT NULL,
    "FRC_STOR_CO" INTEGER NOT NULL,

    CONSTRAINT "store_city_pkey" PRIMARY KEY ("STDR_YYQU_CD","MEGA_CD","SVC_INDUTY_CD")
);

-- CreateTable
CREATE TABLE "store_gu" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "SVC_INDUTY_CD" TEXT NOT NULL,
    "SVC_INDUTY_CD_NM" TEXT NOT NULL,
    "STOR_CO" INTEGER NOT NULL,
    "SIMILR_INDUTY_STOR_CO" INTEGER NOT NULL,
    "OPBIZ_RT" DOUBLE PRECISION NOT NULL,
    "OPBIZ_STOR_CO" INTEGER NOT NULL,
    "CLSBIZ_RT" DOUBLE PRECISION NOT NULL,
    "CLSBIZ_STOR_CO" INTEGER NOT NULL,
    "FRC_STOR_CO" INTEGER NOT NULL,

    CONSTRAINT "store_gu_pkey" PRIMARY KEY ("STDR_YYQU_CD","SIGNGU_CD","SVC_INDUTY_CD")
);

-- CreateTable
CREATE TABLE "store_dong" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "SVC_INDUTY_CD" TEXT NOT NULL,
    "SVC_INDUTY_CD_NM" TEXT NOT NULL,
    "STOR_CO" INTEGER NOT NULL,
    "SIMILR_INDUTY_STOR_CO" INTEGER NOT NULL,
    "OPBIZ_RT" DOUBLE PRECISION NOT NULL,
    "OPBIZ_STOR_CO" INTEGER NOT NULL,
    "CLSBIZ_RT" DOUBLE PRECISION NOT NULL,
    "CLSBIZ_STOR_CO" INTEGER NOT NULL,
    "FRC_STOR_CO" INTEGER NOT NULL,

    CONSTRAINT "store_dong_pkey" PRIMARY KEY ("STDR_YYQU_CD","ADSTRD_CD","SVC_INDUTY_CD")
);

-- CreateTable
CREATE TABLE "store_backarea" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "SVC_INDUTY_CD" TEXT NOT NULL,
    "SVC_INDUTY_CD_NM" TEXT NOT NULL,
    "STOR_CO" INTEGER NOT NULL,
    "SIMILR_INDUTY_STOR_CO" INTEGER NOT NULL,
    "OPBIZ_RT" DOUBLE PRECISION NOT NULL,
    "OPBIZ_STOR_CO" INTEGER NOT NULL,
    "CLSBIZ_RT" DOUBLE PRECISION NOT NULL,
    "CLSBIZ_STOR_CO" INTEGER NOT NULL,
    "FRC_STOR_CO" INTEGER NOT NULL,

    CONSTRAINT "store_backarea_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD","SVC_INDUTY_CD")
);

-- CreateTable
CREATE TABLE "store_commercial" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "SVC_INDUTY_CD" TEXT NOT NULL,
    "SVC_INDUTY_CD_NM" TEXT NOT NULL,
    "STOR_CO" INTEGER NOT NULL,
    "SIMILR_INDUTY_STOR_CO" INTEGER NOT NULL,
    "OPBIZ_RT" DOUBLE PRECISION NOT NULL,
    "OPBIZ_STOR_CO" INTEGER NOT NULL,
    "CLSBIZ_RT" DOUBLE PRECISION NOT NULL,
    "CLSBIZ_STOR_CO" INTEGER NOT NULL,
    "FRC_STOR_CO" INTEGER NOT NULL,

    CONSTRAINT "store_commercial_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD","SVC_INDUTY_CD")
);

-- CreateTable
CREATE TABLE "working_population_city" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "MEGA_CD" TEXT NOT NULL,
    "MEGA_CD_NM" TEXT NOT NULL,
    "TOT_WRC_POPLTN_CO" INTEGER NOT NULL,
    "ML_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FML_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,

    CONSTRAINT "working_population_city_pkey" PRIMARY KEY ("STDR_YYQU_CD","MEGA_CD")
);

-- CreateTable
CREATE TABLE "working_population_gu" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "SIGNGU_CD" TEXT NOT NULL,
    "SIGNGU_CD_NM" TEXT NOT NULL,
    "TOT_WRC_POPLTN_CO" INTEGER NOT NULL,
    "ML_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FML_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,

    CONSTRAINT "working_population_gu_pkey" PRIMARY KEY ("STDR_YYQU_CD","SIGNGU_CD")
);

-- CreateTable
CREATE TABLE "working_population_dong" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "ADSTRD_CD" TEXT NOT NULL,
    "ADSTRD_CD_NM" TEXT NOT NULL,
    "TOT_WRC_POPLTN_CO" INTEGER NOT NULL,
    "ML_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FML_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,

    CONSTRAINT "working_population_dong_pkey" PRIMARY KEY ("STDR_YYQU_CD","ADSTRD_CD")
);

-- CreateTable
CREATE TABLE "working_population_backarea" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "TOT_WRC_POPLTN_CO" INTEGER NOT NULL,
    "ML_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FML_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,

    CONSTRAINT "working_population_backarea_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);

-- CreateTable
CREATE TABLE "working_population_commercial" (
    "STDR_YYQU_CD" TEXT NOT NULL,
    "TRDAR_SE_CD" TEXT NOT NULL,
    "TRDAR_SE_CD_NM" TEXT NOT NULL,
    "TRDAR_CD" TEXT NOT NULL,
    "TRDAR_CD_NM" TEXT NOT NULL,
    "TOT_WRC_POPLTN_CO" INTEGER NOT NULL,
    "ML_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FML_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "AGRDE_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "MAG_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_10_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_20_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_30_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_40_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_50_WRC_POPLTN_CO" INTEGER NOT NULL,
    "FAG_60_ABOVE_WRC_POPLTN_CO" INTEGER NOT NULL,

    CONSTRAINT "working_population_commercial_pkey" PRIMARY KEY ("STDR_YYQU_CD","TRDAR_CD")
);
